# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None)),
                ('quote_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qoutes', models.ManyToManyField(related_name='fav_quotes', to='python_app.User')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_quotes', to='python_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
