# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0002_auto_20170826_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='qoutes',
            new_name='quotes',
        ),
    ]
